version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  task-service:
    build:
      context: ./services/task-service
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka

  notification-service:
    build:
      context: ./services/notification-service
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka

  analytics-service:
    build:
      context: ./services/analytics-service
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka